export const ROUTES = {
  HOME: "/",
  SIGN_UP: "/sign-up",
  SIGN_IN: "/sign-in",
  DASHBOARD: "/dashboard",
  SCHEDULE: "/dashboard/schedule",
  CLIENTS: "/dashboard/clients",
  REQUESTS: "/dashboard/requests",
  QUOTES: "/dashboard/quotes",
  JOBS: "/dashboard/jobs",
  INVOICES: "/dashboard/invoices",
  MARKETING: "/dashboard/marketing",
  REPORTS: "/dashboard/reports",
  EXPENSES: "/dashboard/expenses",
  TIMESHEETS: "/dashboard/timesheets",
  APPS: "/dashboard/apps",
  REFER_AND_FRIEND: "/dashboard/refer-and-friend",
  // ===============BUSINESS MANAGEMENT
  COMPANY_SETTINGS: "/dashboard/account",
  BRANDING: "/dashboard/account/branding",
  PRODUCTS_SERVICES: "/dashboard/account/products-and-services",
  CUSTOM_FIELDS: "/dashboard/account/custom-fields",
  EXPENSE_TRACKING: "/dashboard/account/expense-tracking",
  // ===============TEAM ORGANIZATION
  MANAGE_TEAM: "/dashboard/account/manage-team",
  NEW: "/dashboard/account/manage-team/new",
  WORK_SETTINGS: "/dashboard/account/work-settings",
  SCHEDULE_SETTINGS: "/dashboard/account/schedule-settings",
  LOCATION_SERVICES: "/dashboard/account/location-services",
  ROUTE_OPTIMIZATION: "/dashboard/account/route-optimization",
  JOB_FORMS: "/dashboard/account/job-forms",
  // ===============CLIENT COMMUNICATION
  CLIENT_HUB: "/dashboard/account/client-hub",
  EMAILS: "/dashboard/account/emails",
  REQUESTS_SETTINGS: "/dashboard/account/requests-settings",
  ONLINE_BOOKING: "/dashboard/account/online-booking",
  // ===============WELCOME
  WELCOME_PROFILE: "/welcome/profile",
  WELCOME_BUSINESS: "/welcome/business",
  WELCOME_TOP_PRIORITY: "/welcome/top-priority",
  WELCOME_HEARD_ABOUT_US: "/welcome/heard-about-us",
};
